### ISSUE TITLE
missing import on EZAudioWaveformFromFileExample project device build

### ISSUE THREAD

**Issue by formvoltron** [distraub/AMMeter#2]
latest 0.1.0 EZAudioWaveformFromFileExample does not build on device build.

just a simple missing import.  AVAudioSession unknown symbol

**Comment by distraub** [comment]
Was this issue supposed to be for the AMMeter repo?
I am familiar with EZAudioWaveform, but this repo isn't related to it.

**Comment by formvoltron** [comment]
Doh!  Wrong tab!  sorry!
